version: '3.9'

services:
  broker:
    image: leckijakub/rsww_172127_broker
    hostname: hipotap_broker
    env_file:
      - env.env

  web:
    image: leckijakub/rsww_172127_web
    environment:
      - FLASK_APP=/hipotap_web
      - FLASK_ENV=development
    env_file:
      - env.env
    ports:
      - "17212:5000"
    depends_on:
      - broker

  api_gateway:
    image: leckijakub/rsww_172127_api_gateway
    hostname: hipotap_api_gateway
    depends_on:
      - broker
    env_file:
      - env.env

  customer:
    image: leckijakub/rsww_172127_customer
    depends_on:
      - broker
    env_file:
      - env.env

  offer:
    image: leckijakub/rsww_172127_offer
    depends_on:
      - broker
    env_file:
      - env.env

  order:
    image: leckijakub/rsww_172127_order
    depends_on:
      - broker
    env_file:
      - env.env

  payment:
    image: leckijakub/rsww_172127_payment
    depends_on:
      - broker
    env_file:
      - env.env

  # remove test db when on production
  hipotap_db:
    extends:
      file: hipotap_db/docker-compose.yml
      service: hipotap_db
