version: '3.9'

services:
  broker:
    extends:
      file: broker_service/docker-compose.yml
      service: broker
    networks:
      - hipotap-net

  web:
    extends:
      file: web_service/docker-compose.yml
      service: web
    depends_on:
      - broker
    networks:
      - hipotap-net

  api_gateway:
    extends:
      file: api_gateway/docker-compose.yml
      service: api_gateway
    depends_on:
      - broker
    networks:
      - hipotap-net

  customer:
    extends:
      file: customer_service/docker-compose.yml
      service: customer
    depends_on:
      - broker
      - customer_db
    networks:
      - hipotap-net

  customer_db:
    extends:
      file: customer_service/docker-compose.yml
      service: customer_db
    networks:
      - hipotap-net

  offer:
    extends:
      file: offer_service/docker-compose.yml
      service: offer
    depends_on:
      - broker
      - offer_db
    networks:
      - hipotap-net

  offer_db:
    extends:
      file: offer_service/docker-compose.yml
      service: offer_db
    networks:
      - hipotap-net

networks:
  hipotap-net:
    driver: bridge
