version: '3.9'

services:
  order:
    container_name: hipotap_order
    build:
      context: ..
      dockerfile: order_service/Dockerfile
  order_db:
    container_name: hipotap_order_db
    hostname: hipotap_order_db
    image: postgres:12.10
    environment:
      - POSTGRES_USER=hipotap
      - POSTGRES_PASSWORD=hipotap
      - POSTGRES_DB=order_db
