# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import customer_pb2 as customer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth.proto',
  package='auth',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nauth.proto\x12\x04\x61uth\x1a\x0e\x63ustomer.proto\"c\n\x0e\x41uthResponsePB\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.auth.AuthStatus\x12/\n\rcustomer_data\x18\x02 \x01(\x0b\x32\x18.customer.CustomerDataPB*-\n\nAuthStatus\x12\x06\n\x02OK\x10\x00\x12\x17\n\x13INVALID_CREDENTIALS\x10\x01\x62\x06proto3')
  ,
  dependencies=[customer__pb2.DESCRIPTOR,])

_AUTHSTATUS = _descriptor.EnumDescriptor(
  name='AuthStatus',
  full_name='auth.AuthStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_CREDENTIALS', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=137,
  serialized_end=182,
)
_sym_db.RegisterEnumDescriptor(_AUTHSTATUS)

AuthStatus = enum_type_wrapper.EnumTypeWrapper(_AUTHSTATUS)
OK = 0
INVALID_CREDENTIALS = 1



_AUTHRESPONSEPB = _descriptor.Descriptor(
  name='AuthResponsePB',
  full_name='auth.AuthResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='auth.AuthResponsePB.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customer_data', full_name='auth.AuthResponsePB.customer_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=135,
)

_AUTHRESPONSEPB.fields_by_name['status'].enum_type = _AUTHSTATUS
_AUTHRESPONSEPB.fields_by_name['customer_data'].message_type = customer__pb2._CUSTOMERDATAPB
DESCRIPTOR.message_types_by_name['AuthResponsePB'] = _AUTHRESPONSEPB
DESCRIPTOR.enum_types_by_name['AuthStatus'] = _AUTHSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthResponsePB = _reflection.GeneratedProtocolMessageType('AuthResponsePB', (_message.Message,), dict(
  DESCRIPTOR = _AUTHRESPONSEPB,
  __module__ = 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.AuthResponsePB)
  ))
_sym_db.RegisterMessage(AuthResponsePB)


# @@protoc_insertion_point(module_scope)
