# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hipotap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hipotap.proto',
  package='hipotap',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rhipotap.proto\x12\x07hipotap\"F\n\x0e\x42\x61seResponsePB\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.hipotap.BaseStatus\x12\x0f\n\x07message\x18\x02 \x01(\t*\x1e\n\nBaseStatus\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x62\x06proto3')
)

_BASESTATUS = _descriptor.EnumDescriptor(
  name='BaseStatus',
  full_name='hipotap.BaseStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=98,
  serialized_end=128,
)
_sym_db.RegisterEnumDescriptor(_BASESTATUS)

BaseStatus = enum_type_wrapper.EnumTypeWrapper(_BASESTATUS)
OK = 0
FAIL = 1



_BASERESPONSEPB = _descriptor.Descriptor(
  name='BaseResponsePB',
  full_name='hipotap.BaseResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='hipotap.BaseResponsePB.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='hipotap.BaseResponsePB.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=96,
)

_BASERESPONSEPB.fields_by_name['status'].enum_type = _BASESTATUS
DESCRIPTOR.message_types_by_name['BaseResponsePB'] = _BASERESPONSEPB
DESCRIPTOR.enum_types_by_name['BaseStatus'] = _BASESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseResponsePB = _reflection.GeneratedProtocolMessageType('BaseResponsePB', (_message.Message,), dict(
  DESCRIPTOR = _BASERESPONSEPB,
  __module__ = 'hipotap_pb2'
  # @@protoc_insertion_point(class_scope:hipotap.BaseResponsePB)
  ))
_sym_db.RegisterMessage(BaseResponsePB)


# @@protoc_insertion_point(module_scope)
