# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: offer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='offer.proto',
  package='offer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0boffer.proto\x12\x05offer\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n\rOfferFilterPB\x12\x1c\n\x14list_of_destinations\x18\x01 \x03(\t\"\x97\x02\n\x07OfferPB\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05place\x18\x04 \x01(\t\x12\r\n\x05hotel\x18\x05 \x01(\t\x12\x17\n\x0fmax_adult_count\x18\x06 \x01(\x05\x12\x1a\n\x12max_children_count\x18\x07 \x01(\x05\x12\x13\n\x0bprice_adult\x18\x08 \x01(\x02\x12\x16\n\x0eprice_children\x18\t \x01(\x02\x12.\n\ndate_start\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x64\x61te_end\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"-\n\x0bOfferListPB\x12\x1e\n\x06offers\x18\x01 \x03(\x0b\x32\x0e.offer.OfferPB\"\"\n\x0eOfferRequestPB\x12\x10\n\x08offer_id\x18\x01 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_OFFERFILTERPB = _descriptor.Descriptor(
  name='OfferFilterPB',
  full_name='offer.OfferFilterPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list_of_destinations', full_name='offer.OfferFilterPB.list_of_destinations', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=100,
)


_OFFERPB = _descriptor.Descriptor(
  name='OfferPB',
  full_name='offer.OfferPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='offer.OfferPB.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='offer.OfferPB.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='offer.OfferPB.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='place', full_name='offer.OfferPB.place', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hotel', full_name='offer.OfferPB.hotel', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_adult_count', full_name='offer.OfferPB.max_adult_count', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_children_count', full_name='offer.OfferPB.max_children_count', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_adult', full_name='offer.OfferPB.price_adult', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_children', full_name='offer.OfferPB.price_children', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_start', full_name='offer.OfferPB.date_start', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_end', full_name='offer.OfferPB.date_end', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=382,
)


_OFFERLISTPB = _descriptor.Descriptor(
  name='OfferListPB',
  full_name='offer.OfferListPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offers', full_name='offer.OfferListPB.offers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=429,
)


_OFFERREQUESTPB = _descriptor.Descriptor(
  name='OfferRequestPB',
  full_name='offer.OfferRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offer_id', full_name='offer.OfferRequestPB.offer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=465,
)

_OFFERPB.fields_by_name['date_start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OFFERPB.fields_by_name['date_end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OFFERLISTPB.fields_by_name['offers'].message_type = _OFFERPB
DESCRIPTOR.message_types_by_name['OfferFilterPB'] = _OFFERFILTERPB
DESCRIPTOR.message_types_by_name['OfferPB'] = _OFFERPB
DESCRIPTOR.message_types_by_name['OfferListPB'] = _OFFERLISTPB
DESCRIPTOR.message_types_by_name['OfferRequestPB'] = _OFFERREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OfferFilterPB = _reflection.GeneratedProtocolMessageType('OfferFilterPB', (_message.Message,), dict(
  DESCRIPTOR = _OFFERFILTERPB,
  __module__ = 'offer_pb2'
  # @@protoc_insertion_point(class_scope:offer.OfferFilterPB)
  ))
_sym_db.RegisterMessage(OfferFilterPB)

OfferPB = _reflection.GeneratedProtocolMessageType('OfferPB', (_message.Message,), dict(
  DESCRIPTOR = _OFFERPB,
  __module__ = 'offer_pb2'
  # @@protoc_insertion_point(class_scope:offer.OfferPB)
  ))
_sym_db.RegisterMessage(OfferPB)

OfferListPB = _reflection.GeneratedProtocolMessageType('OfferListPB', (_message.Message,), dict(
  DESCRIPTOR = _OFFERLISTPB,
  __module__ = 'offer_pb2'
  # @@protoc_insertion_point(class_scope:offer.OfferListPB)
  ))
_sym_db.RegisterMessage(OfferListPB)

OfferRequestPB = _reflection.GeneratedProtocolMessageType('OfferRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _OFFERREQUESTPB,
  __module__ = 'offer_pb2'
  # @@protoc_insertion_point(class_scope:offer.OfferRequestPB)
  ))
_sym_db.RegisterMessage(OfferRequestPB)


# @@protoc_insertion_point(module_scope)
