# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: offer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='offer.proto',
  package='offer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0boffer.proto\x12\x05offer\"-\n\rOfferFilterPB\x12\x1c\n\x14list_of_destinations\x18\x01 \x03(\t\"\x18\n\x07OfferPB\x12\r\n\x05title\x18\x01 \x01(\t\"-\n\x0bOfferListPB\x12\x1e\n\x06offers\x18\x01 \x03(\x0b\x32\x0e.offer.OfferPBb\x06proto3')
)




_OFFERFILTERPB = _descriptor.Descriptor(
  name='OfferFilterPB',
  full_name='offer.OfferFilterPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list_of_destinations', full_name='offer.OfferFilterPB.list_of_destinations', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=67,
)


_OFFERPB = _descriptor.Descriptor(
  name='OfferPB',
  full_name='offer.OfferPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='offer.OfferPB.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=93,
)


_OFFERLISTPB = _descriptor.Descriptor(
  name='OfferListPB',
  full_name='offer.OfferListPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offers', full_name='offer.OfferListPB.offers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=140,
)

_OFFERLISTPB.fields_by_name['offers'].message_type = _OFFERPB
DESCRIPTOR.message_types_by_name['OfferFilterPB'] = _OFFERFILTERPB
DESCRIPTOR.message_types_by_name['OfferPB'] = _OFFERPB
DESCRIPTOR.message_types_by_name['OfferListPB'] = _OFFERLISTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OfferFilterPB = _reflection.GeneratedProtocolMessageType('OfferFilterPB', (_message.Message,), dict(
  DESCRIPTOR = _OFFERFILTERPB,
  __module__ = 'offer_pb2'
  # @@protoc_insertion_point(class_scope:offer.OfferFilterPB)
  ))
_sym_db.RegisterMessage(OfferFilterPB)

OfferPB = _reflection.GeneratedProtocolMessageType('OfferPB', (_message.Message,), dict(
  DESCRIPTOR = _OFFERPB,
  __module__ = 'offer_pb2'
  # @@protoc_insertion_point(class_scope:offer.OfferPB)
  ))
_sym_db.RegisterMessage(OfferPB)

OfferListPB = _reflection.GeneratedProtocolMessageType('OfferListPB', (_message.Message,), dict(
  DESCRIPTOR = _OFFERLISTPB,
  __module__ = 'offer_pb2'
  # @@protoc_insertion_point(class_scope:offer.OfferListPB)
  ))
_sym_db.RegisterMessage(OfferListPB)


# @@protoc_insertion_point(module_scope)
