# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='order.proto',
  package='order',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0border.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n\x0eOrderRequestPB\x12\x10\n\x08offer_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x63ustomer_email\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x64ult_count\x18\x03 \x01(\x05\x12\x16\n\x0e\x63hildren_count\x18\x04 \x01(\x05\"\xc3\x01\n\x07OrderPB\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08offer_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x63ustomer_id\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x64ult_count\x18\x04 \x01(\x05\x12\x16\n\x0e\x63hildren_count\x18\x05 \x01(\x05\x12\r\n\x05price\x18\x06 \x01(\x02\x12\x31\n\rcreation_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0epayment_status\x18\x08 \x01(\t\"%\n\x11GetOrderRequestPB\x12\x10\n\x08order_id\x18\x01 \x01(\x05\",\n\x12OrderListRequestPB\x12\x16\n\x0e\x63ustomer_email\x18\x01 \x01(\t\"-\n\x0bOrderListPB\x12\x1e\n\x06orders\x18\x01 \x03(\x0b\x32\x0e.order.OrderPB\"3\n\rPaymentInfoPB\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x13\n\x0b\x63\x61rd_number\x18\x02 \x01(\t\"U\n\x15OrderPaymentRequestPB\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12*\n\x0cpayment_info\x18\x02 \x01(\x0b\x32\x14.order.PaymentInfoPBb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ORDERREQUESTPB = _descriptor.Descriptor(
  name='OrderRequestPB',
  full_name='order.OrderRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offer_id', full_name='order.OrderRequestPB.offer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customer_email', full_name='order.OrderRequestPB.customer_email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='adult_count', full_name='order.OrderRequestPB.adult_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='children_count', full_name='order.OrderRequestPB.children_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=158,
)


_ORDERPB = _descriptor.Descriptor(
  name='OrderPB',
  full_name='order.OrderPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='order.OrderPB.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offer_id', full_name='order.OrderPB.offer_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='order.OrderPB.customer_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='adult_count', full_name='order.OrderPB.adult_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='children_count', full_name='order.OrderPB.children_count', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='order.OrderPB.price', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='order.OrderPB.creation_time', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payment_status', full_name='order.OrderPB.payment_status', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=356,
)


_GETORDERREQUESTPB = _descriptor.Descriptor(
  name='GetOrderRequestPB',
  full_name='order.GetOrderRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='order.GetOrderRequestPB.order_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=395,
)


_ORDERLISTREQUESTPB = _descriptor.Descriptor(
  name='OrderListRequestPB',
  full_name='order.OrderListRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_email', full_name='order.OrderListRequestPB.customer_email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=441,
)


_ORDERLISTPB = _descriptor.Descriptor(
  name='OrderListPB',
  full_name='order.OrderListPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders', full_name='order.OrderListPB.orders', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=488,
)


_PAYMENTINFOPB = _descriptor.Descriptor(
  name='PaymentInfoPB',
  full_name='order.PaymentInfoPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='order.PaymentInfoPB.price', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='card_number', full_name='order.PaymentInfoPB.card_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=541,
)


_ORDERPAYMENTREQUESTPB = _descriptor.Descriptor(
  name='OrderPaymentRequestPB',
  full_name='order.OrderPaymentRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='order.OrderPaymentRequestPB.order_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payment_info', full_name='order.OrderPaymentRequestPB.payment_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=628,
)

_ORDERPB.fields_by_name['creation_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ORDERLISTPB.fields_by_name['orders'].message_type = _ORDERPB
_ORDERPAYMENTREQUESTPB.fields_by_name['payment_info'].message_type = _PAYMENTINFOPB
DESCRIPTOR.message_types_by_name['OrderRequestPB'] = _ORDERREQUESTPB
DESCRIPTOR.message_types_by_name['OrderPB'] = _ORDERPB
DESCRIPTOR.message_types_by_name['GetOrderRequestPB'] = _GETORDERREQUESTPB
DESCRIPTOR.message_types_by_name['OrderListRequestPB'] = _ORDERLISTREQUESTPB
DESCRIPTOR.message_types_by_name['OrderListPB'] = _ORDERLISTPB
DESCRIPTOR.message_types_by_name['PaymentInfoPB'] = _PAYMENTINFOPB
DESCRIPTOR.message_types_by_name['OrderPaymentRequestPB'] = _ORDERPAYMENTREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderRequestPB = _reflection.GeneratedProtocolMessageType('OrderRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _ORDERREQUESTPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderRequestPB)
  ))
_sym_db.RegisterMessage(OrderRequestPB)

OrderPB = _reflection.GeneratedProtocolMessageType('OrderPB', (_message.Message,), dict(
  DESCRIPTOR = _ORDERPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderPB)
  ))
_sym_db.RegisterMessage(OrderPB)

GetOrderRequestPB = _reflection.GeneratedProtocolMessageType('GetOrderRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _GETORDERREQUESTPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.GetOrderRequestPB)
  ))
_sym_db.RegisterMessage(GetOrderRequestPB)

OrderListRequestPB = _reflection.GeneratedProtocolMessageType('OrderListRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _ORDERLISTREQUESTPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderListRequestPB)
  ))
_sym_db.RegisterMessage(OrderListRequestPB)

OrderListPB = _reflection.GeneratedProtocolMessageType('OrderListPB', (_message.Message,), dict(
  DESCRIPTOR = _ORDERLISTPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderListPB)
  ))
_sym_db.RegisterMessage(OrderListPB)

PaymentInfoPB = _reflection.GeneratedProtocolMessageType('PaymentInfoPB', (_message.Message,), dict(
  DESCRIPTOR = _PAYMENTINFOPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.PaymentInfoPB)
  ))
_sym_db.RegisterMessage(PaymentInfoPB)

OrderPaymentRequestPB = _reflection.GeneratedProtocolMessageType('OrderPaymentRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _ORDERPAYMENTREQUESTPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderPaymentRequestPB)
  ))
_sym_db.RegisterMessage(OrderPaymentRequestPB)


# @@protoc_insertion_point(module_scope)
