# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='order.proto',
  package='order',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0border.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n\x0eOrderRequestPB\x12\x16\n\x0e\x63ustomer_email\x18\x01 \x01(\t\x12\x10\n\x08offer_id\x18\x02 \x01(\x05\x12\x18\n\x10number_of_adults\x18\x03 \x01(\x05\x12\x1a\n\x12number_of_children\x18\x04 \x01(\x05\x12\r\n\x05price\x18\x05 \x01(\x02\"\x9f\x01\n\x07OrderPB\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08offer_id\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x18\n\x10number_of_adults\x18\x04 \x01(\x05\x12\x1a\n\x12number_of_children\x18\x05 \x01(\x05\x12\x31\n\rcreation_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\",\n\x12OrderListRequestPB\x12\x16\n\x0e\x63ustomer_email\x18\x01 \x01(\t\"-\n\x0bOrderListPB\x12\x1e\n\x06orders\x18\x01 \x03(\x0b\x32\x0e.order.OrderPBb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ORDERREQUESTPB = _descriptor.Descriptor(
  name='OrderRequestPB',
  full_name='order.OrderRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_email', full_name='order.OrderRequestPB.customer_email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offer_id', full_name='order.OrderRequestPB.offer_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_adults', full_name='order.OrderRequestPB.number_of_adults', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_children', full_name='order.OrderRequestPB.number_of_children', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='order.OrderRequestPB.price', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=182,
)


_ORDERPB = _descriptor.Descriptor(
  name='OrderPB',
  full_name='order.OrderPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='order.OrderPB.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offer_id', full_name='order.OrderPB.offer_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='order.OrderPB.price', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_adults', full_name='order.OrderPB.number_of_adults', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_children', full_name='order.OrderPB.number_of_children', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='order.OrderPB.creation_time', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=344,
)


_ORDERLISTREQUESTPB = _descriptor.Descriptor(
  name='OrderListRequestPB',
  full_name='order.OrderListRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_email', full_name='order.OrderListRequestPB.customer_email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=390,
)


_ORDERLISTPB = _descriptor.Descriptor(
  name='OrderListPB',
  full_name='order.OrderListPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders', full_name='order.OrderListPB.orders', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=437,
)

_ORDERPB.fields_by_name['creation_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ORDERLISTPB.fields_by_name['orders'].message_type = _ORDERPB
DESCRIPTOR.message_types_by_name['OrderRequestPB'] = _ORDERREQUESTPB
DESCRIPTOR.message_types_by_name['OrderPB'] = _ORDERPB
DESCRIPTOR.message_types_by_name['OrderListRequestPB'] = _ORDERLISTREQUESTPB
DESCRIPTOR.message_types_by_name['OrderListPB'] = _ORDERLISTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderRequestPB = _reflection.GeneratedProtocolMessageType('OrderRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _ORDERREQUESTPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderRequestPB)
  ))
_sym_db.RegisterMessage(OrderRequestPB)

OrderPB = _reflection.GeneratedProtocolMessageType('OrderPB', (_message.Message,), dict(
  DESCRIPTOR = _ORDERPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderPB)
  ))
_sym_db.RegisterMessage(OrderPB)

OrderListRequestPB = _reflection.GeneratedProtocolMessageType('OrderListRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _ORDERLISTREQUESTPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderListRequestPB)
  ))
_sym_db.RegisterMessage(OrderListRequestPB)

OrderListPB = _reflection.GeneratedProtocolMessageType('OrderListPB', (_message.Message,), dict(
  DESCRIPTOR = _ORDERLISTPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderListPB)
  ))
_sym_db.RegisterMessage(OrderListPB)


# @@protoc_insertion_point(module_scope)
