# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='order.proto',
  package='order',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0border.proto\x12\x05order\"I\n\x0eOrderRequestPB\x12\x16\n\x0e\x63ustomer_email\x18\x01 \x01(\t\x12\x10\n\x08offer_id\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\x62\x06proto3')
)




_ORDERREQUESTPB = _descriptor.Descriptor(
  name='OrderRequestPB',
  full_name='order.OrderRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_email', full_name='order.OrderRequestPB.customer_email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offer_id', full_name='order.OrderRequestPB.offer_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='order.OrderRequestPB.price', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['OrderRequestPB'] = _ORDERREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderRequestPB = _reflection.GeneratedProtocolMessageType('OrderRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _ORDERREQUESTPB,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderRequestPB)
  ))
_sym_db.RegisterMessage(OrderRequestPB)


# @@protoc_insertion_point(module_scope)
