from re import A


API_GATEWAY_URL = "http://hipotap_api_gateway:8000"

AUTHENTICATE_PATH = "/customer/authenticate/"
AUTHENTICATE_ENDPOINT = API_GATEWAY_URL + AUTHENTICATE_PATH

REGISTER_PATH = "/customer/register/"
REGISTER_ENDPOINT = API_GATEWAY_URL + REGISTER_PATH

OFFERS_LIST_PATH = "/offers/"
OFFERS_ENDPOINT = API_GATEWAY_URL + OFFERS_LIST_PATH

ORDER_REQUEST_PATH = "/order/order_offer/"
ORDER_REQUEST_ENDPOINT = API_GATEWAY_URL + ORDER_REQUEST_PATH

ORDER_LIST_PATH = "/orders/"
ORDER_LIST_ENDPOINT = API_GATEWAY_URL + ORDER_LIST_PATH
