from re import A


API_GATEWAY_URL = "http://hipotap_api_gateway:8000"

AUTHENTICATE_PATH = "/customer/authenticate/"
AUTHENTICATE_ENDPOINT = API_GATEWAY_URL + AUTHENTICATE_PATH

REGISTER_PATH = "/customer/register/"
REGISTER_ENDPOINT = API_GATEWAY_URL + REGISTER_PATH

OFFERS_LIST_PATH = "/offers/"
OFFERS_ENDPOINT = API_GATEWAY_URL + OFFERS_LIST_PATH

OFFER_PATH = "/offer/"
OFFER_ENDPOINT = API_GATEWAY_URL + OFFER_PATH

ORDER_RESERVE_REQUEST_PATH = "/order/order_reserve_offer/"
ORDER_RESERVE_REQUEST_ENDPOINT = API_GATEWAY_URL + ORDER_RESERVE_REQUEST_PATH

ORDER_LIST_PATH = "/orders/"
ORDER_LIST_ENDPOINT = API_GATEWAY_URL + ORDER_LIST_PATH

GET_ORDER_PATH = '/order/'
GET_ORDER_ENDPOINT = API_GATEWAY_URL + GET_ORDER_PATH

ORDER_PAYMENT_PATH = "/order/order_payment/"
ORDER_PAYMENT_ENDPOINT = API_GATEWAY_URL + ORDER_PAYMENT_PATH
